# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/RoundTheCode.AzureTestProject.sln'
  project: '**/RoundTheCode.AzureTestProject.csproj'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: NuGetToolInstaller@1
            name: 'NuGetToolInstaller'
            displayName: 'NuGet tool installer'
            

          - task: NuGetCommand@2
            name: 'NuGetRestore'
            displayName: 'NuGet restore packages'
            inputs:
              command: 'restore'
              restoreSolution: '$(solution)'
              feedsToUse: 'select'

          - task: DotNetCoreCLI@2
            name: 'Tests'
            displayName: 'Run Tests'
            inputs:
              command: 'test'
              projects: '$(solution)'
              arguments: '--configuration $(BuildConfiguration)'


          - task: DotNetCoreCLI@2
            name: 'Publish'
            displayName: 'Publish'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(project)'
              arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: false

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'AzureTestProject'
              publishLocation: 'Container'

  - stage: QA
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: 'QA Deploy'
    jobs:
    - deployment: QADeployment
      environment: 'Windows 11 server.Machine3'
      strategy:
        runOnce:
          deploy:
            steps:
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'AzureTestProject'
                    downloadPath: '$(System.ArtifactsDirectory)'
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StopIIS'
                  displayName: 'Stop IIS Website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: 'AzureTestProject'
                
                - task: IISWebAppDeploymentOnMachineGroup@0
                  inputs:
                    WebSiteName: 'AzureTestProject'
                    Package: '$(System.ArtifactsDirectory)/AzureTestProject/RoundTheCode.AzureTestProject'


                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIIS'
                  displayName: 'Start IIS Website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: 'AzureTestProject'

  - stage: QAApproval
    displayName: 'QA Approval'
    dependsOn: QA
    condition: succeeded('QA')
    jobs:
      - deployment: QAApproval
        displayName: 'Manual QA Approval'
        environment: 'QAApprovalEnvironment'
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: ManualValidation@0
                  displayName: 'Manual QA Approval'
                  inputs:
                    notifyUsers: 'rodger.yonley@protonmail.com'
                    instructions: 'Please QA the release environment'

  - stage: ManagerApproval
    displayName: 'Manager Approval'
    dependsOn: QAApproval
    condition: succeeded('QAApproval')
    jobs:
      - deployment: ManagerApproval
        displayName: 'Manager Approval Job'
        environment: 'ManagerApprovalEnvironment'
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: ManualValidation@0
                  displayName: 'Manual Manager Approval'
                  inputs:
                    notifyUsers: 'rodger.yonley@protonmail.com'
                    instructions: 'Please approve the release for production deployment'
                    
  - stage: Prod
    dependsOn: ManagerApproval
    condition: and(succeeded('ManagerApproval'), succeeded())
    displayName: 'Prod Deploy'
    jobs:
    - deployment: ProdDeployment
      environment: 'Windows 11 Production.Machine3'
      strategy:
        runOnce:
          deploy:
            steps:
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'AzureTestProject'
                    downloadPath: '$(System.ArtifactsDirectory)'
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StopIIS'
                  displayName: 'Stop IIS Website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: 'AzureTestProjectProd'
                
                - task: IISWebAppDeploymentOnMachineGroup@0
                  inputs:
                    WebSiteName: 'AzureTestProjectProd'
                    Package: '$(System.ArtifactsDirectory)/AzureTestProject/RoundTheCode.AzureTestProject'


                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIIS'
                  displayName: 'Start IIS Website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: 'AzureTestProjectProd'                  